SEED_PRODUCTS = [
    {
        "id": "p-100",
        "name": "AeroFit Wireless Earbuds",
        "category": "Audio",
        "price": 79,
        "rating": 4.5,
        "description": "Sweat resistant earbuds with punchy bass, secure fins, and 28 hour case battery.",
        "tags": ["workout", "earbuds", "wireless", "gym", "water resistant"],
        "short_reason": "they are secure, sweat resistant, and stay under $100.",
    },
    {
        "id": "p-101",
        "name": "QuietNest ANC Headphones",
        "category": "Audio",
        "price": 149,
        "rating": 4.7,
        "description": "Over-ear headphones with active noise cancellation for travel, calls, and focus.",
        "tags": ["noise cancelling", "travel", "office", "headphones"],
        "short_reason": "the noise cancellation and comfort are strongest for travel and office work.",
    },
    {
        "id": "p-102",
        "name": "StrideLite Running Shoes",
        "category": "Footwear",
        "price": 89,
        "rating": 4.4,
        "description": "Lightweight running shoes with breathable mesh and responsive foam.",
        "tags": ["running", "shoes", "lightweight", "fitness"],
        "short_reason": "they are lightweight, breathable, and built for daily runs.",
    },
    {
        "id": "p-103",
        "name": "TrailGuard Hiking Backpack",
        "category": "Outdoor",
        "price": 119,
        "rating": 4.6,
        "description": "Weather resistant 32L backpack with laptop sleeve and hydration pocket.",
        "tags": ["hiking", "travel", "backpack", "outdoor", "water resistant"],
        "short_reason": "it has enough capacity for hikes while still working as a travel bag.",
    },
    {
        "id": "p-104",
        "name": "DeskFlow Ergonomic Chair",
        "category": "Office",
        "price": 229,
        "rating": 4.8,
        "description": "Adjustable office chair with lumbar support, mesh back, and tilt lock.",
        "tags": ["office", "chair", "ergonomic", "work from home"],
        "short_reason": "the adjustable support is best for long desk sessions.",
    },
    {
        "id": "p-105",
        "name": "BrewMate Go Coffee Maker",
        "category": "Kitchen",
        "price": 64,
        "rating": 4.3,
        "description": "Compact single serve coffee maker for dorm rooms, apartments, and travel.",
        "tags": ["coffee", "kitchen", "compact", "travel"],
        "short_reason": "it is compact, affordable, and easy to fit into small spaces.",
    },
]
